import Footer from './components/Footer/Footer'
import Navbar from './components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* الحاوية الرئيسية */}
        <div className="max-w-screen-md  overflow-hidden  lg:max-w-screen-lg xl:max-w-screen-xl xxl:max-w-screen-xxl mx-auto flex flex-col min-h-screen justify-between ">


          {/* الـ Navbar */}
          <Navbar />

          {/* المحتوى الرئيسي */}

          <main className='flex-1'> {children}</main>


          {/* الـ Footer */}
          <Footer />
        </div>
      </body>
    </html>
  )
}
